### ISSUE TITLE
Formato de 2 únicos valores numa coluna inválidos no goodtables

### ISSUE THREAD

**Issue by Andrelamor** [dados-mg/termos-parceria-contratos-gestao#1]
Correção indicada [neste coment](https://github.com/dados-mg/termos-parceria-contratos-gestao/issues/1#issuecomment-734963000) realizada, dados validados 

Job correspondente: https://goodtables.io/github/dados-mg/termos-parceria-contratos-gestao/jobs/21

**Comment by Andrelamor** [comment]
Após ajustar propriedades de datas e valores monetários (vide [commit](https://github.com/dados-mg/termos-parceria-contratos-gestao/commit/e4d22b0c5086e18e8106b88afc1d5e10e3cea63d)), goodtables acusou inconsistência de formato em apenas dois valores em uma coluna inteira: https://goodtables.io/github/dados-mg/termos-parceria-contratos-gestao

**Comment by fjuniorr** [comment]
@Andrelamor acho que ele lançou erro porque 31 não é um mês válido. No arquivo original tá assim? Parece uma troca, e o valor deveria ser `20200331`.

Ps. O formato `any` vai aceitar qualquer coisa na data, mas misturar representações na mesma coluna acho má ideia. Acho que com `"format": "%Y%m%d"` ele vai aceitar somente datas `YYYYMMDD`.
