### ISSUE TITLE
Recurso do conjunto de dados sem opção para baixar csv 

### ISSUE THREAD

**Issue by fjuniorr** [dados-mg/termos-parceria-contratos-gestao#2]
Entrei agora nesse conjunto e o [recurso](http://dados.mg.gov.br/dataset/termos-parceria-contratos-gestao/resource/f66ad9dc-090a-4c0f-9da0-def65046e4b7) não dá a opção de baixar o csv

![Termos_de_Parceria_e_Contratos_de_Gestão_-_Termos_de_Parceria_e_Contratos_de_Gestão_-_Portal_de_Dados_Abertos_do_Estado_de_Minas_Gerais](https://user-images.githubusercontent.com/4969445/108057753-cd990c80-7031-11eb-9c69-91d3b0a33c35.png)

Vide [conjunto do selo amigo do estado](http://dados.mg.gov.br/dataset/doacoes-comodatos-amigo-estado-mg/resource/83adf097-d4fe-4d6d-8e36-459c1c43907f)

![Doações_e_comodatos_recebidos_pela_Administração_-_Selo_Amigo_de_Minas_Gerais_-_Doações_e_comodatos_recebidos_pela_Administração_-_Selo_Amigo_de_Minas_Gerais_-_Portal_de_Dados_Abertos_do_Estado_de_Minas_Gerais](https://user-images.githubusercontent.com/4969445/108057910-0802a980-7032-11eb-8357-dbb9a9789676.png)

@Andrelamor você lembra de algo diferente na atualização desse recurso?

**Comment by Andrelamor** [comment]
@fjuniorr parece que ele não carregou o arquivo, veja a diferença:

* Termos de Parceria:

![image](https://user-images.githubusercontent.com/52294411/108121077-fb597200-7080-11eb-88c7-0de33d7f41c8.png)

* Doações:

![image](https://user-images.githubusercontent.com/52294411/108121163-1fb54e80-7081-11eb-91bb-b45b38a69461.png)
